/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package hello_17

import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._

object FinTest {
  def main(args: Array[String]) {
    val spark = SparkSession
      .builder
      .config("spark.cassandra.connection.host", "localhost")
      .config("spark.cassandra.auth.username", "cassandra")
      .config("spark.cassandra.auth.password", "cassandra")
      .appName("写入clickhouse数据")
      .getOrCreate()
    
    import spark.implicits._

    val df = spark
      .read
      .format("org.apache.spark.sql.cassandra")
      .options(Map(
        "table" -> "brch_qry_dtl",
        "keyspace" -> "finance"))
      .load

    df.write
      .format("jdbc")
      .option("driver", "ru.yandex.clickhouse.ClickHouseDriver")
      .option("url", "jdbc:clickhouse://localhost:8123/finance")
      .option("user", "hzg")
      .option("password", "1234")
      .option("dbtable", "brch_qry_dtl")
      .option("batchsize", 10000)
      .option("isolationLevel", "NONE")
      .mode("append")
      .save

    spark.stop()
  }
}