/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package hello_02

import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._

object FinTest {
  def main(args: Array[String]) {
    val spark = SparkSession
      .builder
      .config("spark.cassandra.connection.host", "localhost")
      .config("spark.cassandra.auth.username", "cassandra")
      .config("spark.cassandra.auth.password", "cassandra")
      .appName("写入cassandra数据")
      .getOrCreate()
    
    import spark.implicits._

    val df = spark.read.options(Map("inferSchema"->"true","delimiter"->",","header"->"true"))
                        .csv("file:///home/hzg/work/helloSpark/data-files/data.csv")
    df.createOrReplaceTempView("qry_dtl")

    df.write
      .format("org.apache.spark.sql.cassandra")
      .options(Map("table" -> "brch_qry_dtl", "keyspace" -> "finance"))
      .save()

    spark.stop()
  }
}